ASPECT_KEYWORDS: dict[str, set[str]] = {
    "price": {
        "affordable",
        "budget",
        "cheap",
        "cost",
        "costly",
        "deal",
        "discount",
        "expensive",
        "money",
        "overpriced",
        "price",
        "priced",
        "pricing",
        "value",
    },
    "quality": {
        "build",
        "broken",
        "durable",
        "fabric",
        "finish",
        "material",
        "performance",
        "quality",
        "reliable",
        "sturdy",
        "works",
    },
    "delivery": {
        "arrived",
        "courier",
        "delay",
        "delayed",
        "delivered",
        "delivery",
        "late",
        "logistics",
        "shipping",
        "slow",
        "tracking",
    },
    "packaging": {
        "box",
        "packed",
        "package",
        "packaging",
        "parcel",
        "sealed",
        "wrap",
        "wrapped",
    },
}

POSITIVE_WORDS = {
    "amazing",
    "best",
    "comfortable",
    "durable",
    "excellent",
    "fast",
    "good",
    "great",
    "happy",
    "impressed",
    "love",
    "loved",
    "nice",
    "perfect",
    "premium",
    "quick",
    "recommend",
    "reliable",
    "satisfied",
    "sturdy",
    "superb",
    "worth",
}

NEGATIVE_WORDS = {
    "awful",
    "bad",
    "broken",
    "cheaply",
    "complaint",
    "costly",
    "damaged",
    "defective",
    "delay",
    "delayed",
    "disappointed",
    "expensive",
    "hate",
    "late",
    "missing",
    "overpriced",
    "poor",
    "refund",
    "return",
    "slow",
    "terrible",
    "unhappy",
    "worst",
}

NEGATIONS = {"not", "never", "no", "hardly", "barely", "without"}
