apiVersion: v1
kind: Service
metadata:
  name: review-analyzer-api
  namespace: review-analyzer
spec:
  selector:
    app: review-analyzer-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
