apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: review-analyzer-ingress
  namespace: review-analyzer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: review-analyzer.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: review-analyzer-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-analyzer-dashboard
                port:
                  number: 8501
